More summary improvements.
es-meta/esmeta pull request #122
Opened 2022-12-09 06:58 UTC by doehyunbaek

This PR contains series of commits to improve upon #119.

With additional info about filtered test262 tests provided with changes in #119, this PR puts them inside Summray.scala.

2022-12-09 06:59 UTC, doehyunbaek commented
I think it would be best to squash and rebase for merge. If needed, I wll rebase and tidy up commits.

2022-12-09 08:44 UTC, jhnaldo requested changes
Please apply the suggestions.

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/test262/Test262.scala
> +
```suggestion
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/test262/Test262.scala
> +
```suggestion
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/test262/util/TestFilter.scala
> +    lift("yet" -> (test => !withYet && yets.contains(removedExt(test.relName)))),
Please redefine `yets` using the string `"not yet categorized tests"` because it still extracts data from `manualConfig.filtered` using the string `"yet tests"` in L134-L135 as follows:
```scala
lazy val yets =
    manualConfig.filtered.getOrElse("yet tests", Nil).toSet
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/util/Summary.scala
> +import java.io.PrintWriter
```suggestion
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/util/Summary.scala
> +      if (notSupportedCount == 1) "NOTSUPPORTED"
```suggestion
      if (notSupportedCount == 1) "NOT-SUPPORTED"
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/error/NotSupported.scala
> +case class NotSupported(reasons: NotSupported.ReasonPath)
```suggestion
case class NotSupported(reasonPath: NotSupported.ReasonPath)
```

2022-12-09 08:44 UTC, jhnaldo commented on src/test/scala/esmeta/ESMetaTest.scala
> +  case class NotSupported(reason: List[String]) extends Result
```suggestion
  case class NotSupported(reasonPath: ReasonPath) extends Result
```

2022-12-09 08:44 UTC, jhnaldo commented on src/test/scala/esmeta/ESMetaTest.scala
> +    case NotSupported(reason) => Json.fromValues(reason.map(Json.fromString))
```suggestion
    case NotSupported(reasonPath) => Json.fromValues(reasonPath.map(Json.fromString))
```

2022-12-09 08:44 UTC, jhnaldo commented on src/test/scala/esmeta/ESMetaTest.scala
> +          resMap += name -> NotSupported(reason)
```suggestion
        case e @ NSError(reasonPath) =>
          resMap += name -> NotSupported(reasonPath)
```

2022-12-09 08:44 UTC, jhnaldo commented on src/test/scala/esmeta/ESMetaTest.scala
> +import esmeta.error.{NotSupported => NSError}
```suggestion
import esmeta.error.{NotSupported => NSError}
import esmeta.error.NotSupported.*
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/util/Summary.scala
>        app >> f"- total: $total%,d" >> LINE_SEP
```suggestion
      app >> f"- time: $time"
      app :> f"- total: $total%,d"
```

2022-12-09 08:44 UTC, jhnaldo commented on src/main/scala/esmeta/util/Summary.scala
> +      notSupported.dumpTo("notsupported", s"$baseDir/notsupported.json")
```suggestion
      notSupported.dumpTo("not-supported", s"$baseDir/not-supported.json")
```

2022-12-11 06:54 UTC, jhnaldo commented on src/test/scala/esmeta/ESMetaTest.scala
> +  case class NotSupported(reason: List[String]) extends Result
Can you please utilize the `ReasonPath` type instead of `List[String]`?

2022-12-11 07:11 UTC, jhnaldo approved these changes
LGTM! 👍

2022-12-11 07:12 UTC, merged