Concurrent execution of Test262Test
es-meta/esmeta pull request #171
Opened 2023-07-30 08:38 UTC by doehyunbaek

Support concurrent execution of Test262Test, this is mainly for performance reason.

For the Linux desktop with 12900F, this reduces test time of whole suite from  01:22:22 to 16:41, the benefit may vary between the systems.

Support serial extraction of ecma262 specification. This is mainly to help debugging as debugging concurrent execution of Extractor was a little bit confusing.

2023-07-30 08:38 UTC, doehyunbaek commented
I will fix the compl test today.

2023-08-04 07:44 UTC, jhnaldo requested changes

2023-08-04 07:44 UTC, jhnaldo commented on src/main/scala/esmeta/extractor/Extractor.scala
> +  ): Spec = new Extractor(document, version, eval, concurrent).result
Is it necessary to support concurrent extraction for concurrent Test262 testing?

2023-08-04 07:44 UTC, jhnaldo commented on src/main/scala/esmeta/phase/Test262Test.scala
> +      warn("progress bar may be unstable in concurrent mode.")
Is it impossible to resolve this issue?

2023-08-04 07:44 UTC, jhnaldo commented on src/main/scala/esmeta/util/ProgressBar.scala
> +    if (concurrent)
Is it possible to design a more unified form?

2023-08-07 06:37 UTC, doehyunbaek commented on src/main/scala/esmeta/extractor/Extractor.scala
> +  ): Spec = new Extractor(document, version, eval, concurrent).result
Not necessary. Excluded from this PR.

2023-08-07 06:37 UTC, doehyunbaek commented on src/main/scala/esmeta/phase/Test262Test.scala
> +      warn("progress bar may be unstable in concurrent mode.")
Resolved with https://github.com/es-meta/esmeta/pull/171/files#diff-eaae679fb425688c5603f0abb743dd3c8150770095868ba59a4b913486406b04R34

2023-08-07 06:38 UTC, doehyunbaek commented on src/main/scala/esmeta/util/ProgressBar.scala
> +    if (concurrent)
Tried with https://github.com/es-meta/esmeta/pull/171/files#diff-f61fd7e6c4e7d373cb7247e2a26c4354361fc73c96f4e9189176365bc6cd30f5R82-R89 .

2023-08-07 10:10 UTC, doehyunbaek commented
I observed the execution of concurrent execution diverging from the serial one. Will open again after I investigate the cause.

2023-08-07 11:27 UTC, doehyunbaek commented
> I observed the execution of concurrent execution diverging from the serial one. Will open again after I investigate the cause.

Sorry, there was no discrepancy. There was a change from number of passing tests from [this commit](https://github.com/es-meta/esmeta/actions/runs/5619109352/job/15225697923) to [this commit](https://github.com/es-meta/esmeta/actions/runs/5758340815/job/15610737207), which made a confusion.

I confirmed the concurrent and serial version outputting the exact same summary

2023-08-13 08:27 UTC, jhnaldo approved these changes
I slightly refactored this PR and supported the progress bar with the concurrent `Summary`. After passing the CI system, I will merge it.

2023-08-13 08:49 UTC, merged